In [1]:
import numpy as np

In [13]:
def state_to_ind(state: np.ndarray):
   n = state.shape[0]
   bases = 4 ** np.arange(n)
   ind = int(np.sum(state * bases))
   return ind

def ind_to_state(ind: int, num_qubits):
   state = np.zeros(num_qubits, dtype=int)
   for i in range(num_qubits):
      r = ind % (4 ** (i+1))
      q = r // (4 ** i)
      state[i] = int(q)
   return state

In [21]:
state_to_ind(ind_to_state(62, 3))

62

In [22]:
np.prod(np.array([1,3,5,2]))

30

In [28]:
from itertools import product
list(product( ))

[(['0', '1', '2', '3'],), (['0', '1', '2', '3'],)]

In [29]:
[['0','1','2','3'] for _ in range(2)]

[['0', '1', '2', '3'], ['0', '1', '2', '3']]

In [34]:
str_state = ''.join(np.arange(5).astype(str))
str_state

'01234'

In [40]:
def str_to_state(str_state, num_qubits):
   out = [int(str_state[i]) for i in range(len(str_state))]
   out += [0] * (num_qubits - len(str_state))
   return np.array(out)

In [41]:
str_to_state('01234', 7)

array([0, 1, 2, 3, 4, 0, 0])

In [43]:
from index import idx, coeff
print(idx)
print(coeff)

[[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]
[[ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
 [ 1.+0.j  1.+0.j  0.+1.j -0.-1.j]
 [ 1.+0.j -0.-1.j  1.+0.j  0.+1.j]
 [ 1.+0.j  0.+1.j -0.-1.j  1.+0.j]]


In [45]:
[i for i,j in zip([1,2], [2,3])]

[1, 2]

In [47]:
from helper import sigma_sx, sigma_sz
np.linalg.eigvals(sigma_sx + sigma_sz)

array([ 1.41421356+0.j, -1.41421356+0.j])